name: tissue-model-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - albumentations
  - boost
  - cxx-compiler
  - dask
  - gudhi
  - jupyterlab
  - matplotlib
  - networkx
  - opencv
  - python=3.10
  - scikit-learn
  - scipy
  - setuptools
  - tensorflow
  - keras-tuner
  - pillow
  - scikit-image
  - tqdm
