name: tissue-model-analysis
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - boost
  - cxx-compiler
  - dask
  - gudhi
  - jupyterlab
  - matplotlib
  - networkx
  - opencv
  - python=3.10
  - scikit-learn
  - setuptools
  - tensorflow
  - keras-tuner
  - pytorch
  - torchvision
  - pillow
