name: tissue-model-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - albumentations
  - boost
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - dask
  - gudhi
  - ipykernel
  - jupyterlab
  - matplotlib
  - networkx
  - opencv
  - pip
  - python=3.10
  - scikit-learn
  - scikit-image
  - setuptools
  - pip:
    - keras-tuner
    - tensorflow
