name: fogg-lab
channels:
  - defaults
  - apple
dependencies:
  - dask=2022.5.0
  - numpy=1.21.5
  - opencv=4.5.4
  - pandas=1.4.2
  - pip=21.2.4
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - tensorflow-deps=2.8.0
  - pip:
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - tensorflow-macos==2.9.0
    - tensorflow-metal==0.5.0
    - protobuf==3.20.*
