name: fogg-lab
channels:
  - defaults
  - apple
dependencies:
  - dask=2022.5.0
  - opencv=4.5.4
  - pandas=1.4.2
  - numpy==1.22.3
  - pip=21.2.4
  - scikit-learn=1.0.2
  - setuptools=61.2.0
  - tensorflow-deps=2.9.0
  - pip:
    - keras==2.9.0rc0
    - keras-preprocessing==1.1.2
    - tensorflow-macos==2.9.0
    - tensorflow-metal==0.5.0
    - protobuf==3.20.*
