name: tissue-model-analysis
channels:
  - conda-forge
dependencies:
  - albumentations=1.4.1
  - boost=1.84.0
  - click=8.1.7
  - dask=2024.5.2
  - gudhi=3.9.0
  - imagecodecs=2024.1.1
  - ipykernel=6.29.3
  - networkx=3.3
  - numpy=1.26.4
  - opencv=4.9.0
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - python=3.10.13
  - scikit-image=0.22.0
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - tifffile=2024.5.22
  - tqdm=4.66.4
  - pip:
      - keras-tuner==1.4.7
      - pyometiff==1.0.0
      - tensorflow==2.15.1
