name: fogg-lab-tissue-model-analysis-tools-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - abseil-cpp=20210324.2
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - blinker=1.4
  - bokeh=2.4.2
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.15.0
  - cgal-cpp=5.3.1
  - charset-normalizer=2.0.12
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=36.0.1
  - cudatoolkit=11.3.1
  - cudnn=8.2.1.32
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask=2022.3.0
  - dask-core=2022.3.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.3.0
  - eigen=3.4.0
  - entrypoints=0.4
  - executing=0.8.3
  - flatbuffers=2.0.0
  - flit-core=3.7.1
  - fonttools=4.29.1
  - freeglut=3.2.2
  - freetype=2.10.4
  - frozenlist=1.3.0
  - fsspec=2022.2.0
  - future=0.18.2
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.44.0
  - gudhi=3.5.0
  - h5py=3.6.0
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.11.2
  - importlib_resources=5.4.0
  - intel-openmp=2022.0.0
  - ipykernel=6.9.1
  - ipython=8.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jasper=2.0.33
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyterlab=3.3.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.2
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.81.0
  - libdeflate=1.10
  - libffi=3.4.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.5.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - llvmlite=0.38.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.6
  - markupsafe=2.1.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2022.0.0
  - mpfr=4.1.0
  - mpir=3.0.0
  - msgpack-python=1.0.3
  - msys2-conda-epoch=20160418
  - multidict=6.0.2
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.11
  - nbconvert=6.4.2
  - nbformat=5.1.3
  - nest-asyncio=1.5.4
  - networkx=2.7.1
  - nodejs=17.9.0
  - notebook=6.4.8
  - numba=0.55.1
  - numpy=1.21.5
  - oauthlib=3.2.0
  - opencv=4.5.1
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.4.1
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.0.3
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.27
  - protobuf=3.17.2
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - py-opencv=4.5.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pynndescent=0.5.6
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.10
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pywin32=303
  - pywinpty=1.1.6
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - seaborn=0.11.0
  - send2trash=1.8.0
  - setuptools=60.9.3
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - sqlite=3.37.0
  - stack_data=0.2.0
  - tabulate=0.8.9
  - tbb=2021.5.0
  - tblib=1.7.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.6.0
  - termcolor=1.1.0
  - terminado=0.13.2
  - terminaltables=3.1.10
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2021e
  - ucrt=10.0.20348.0
  - umap-learn=0.5.2
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.1
  - werkzeug=2.0.3
  - wheel=0.35.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.13.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zict=2.1.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - keras-tuner==1.1.2
