name: tissue-model-analysis
channels:
  - conda-forge
dependencies:
  - albumentations=1.4.1
  - boost=1.84.0
  - dask=2024.5.1
  - gudhi=3.9.0
  - imagecodecs=2024.1.1
  - jupyterlab=4.2.1
  - matplotlib=3.8.4
  - networkx=3.3
  - opencv=4.9.0
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - python=3.10.13
  - scikit-image=0.22.0
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - tifffile=2024.5.22
  - tqdm=4.66.4
  - pip:
      - keras==2.13.1
      - keras-tuner==1.4.7
      - numpy==1.24.3
      - tensorflow[with-gpu]==2.13.0
      - pyometiff==1.0.0
