name: tissue-model-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - albumentations
  - boost
  - dask
  - gudhi
  - jupyterlab
  - matplotlib
  - networkx
  - opencv
  - python>=3.8
  - scikit-learn
  - scipy
  - setuptools
  - tensorflow
  - keras-tuner
  - pillow
  - scikit-image
  - tqdm
