name: tissue-model-analysis
channels:
  - conda-forge
dependencies:
  - albumentations=1.4.1
  - anyio=4.3.0
  - aom=3.9.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - blosc=1.21.5
  - bokeh=3.4.1
  - boost=1.84.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.14.4
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.5.1
  - dask-core=2024.5.1
  - dask-expr=1.1.1
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.5.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2024.5.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gudhi=3.9.0
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - imagecodecs=2024.1.1
  - imageio=2.34.1
  - imath=3.1.11
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - isoduration=20.11.0
  - jasper=4.2.4
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=2.4
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libavif16=1.0.4
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-devel=1.84.0
  - libboost-headers=1.84.0
  - libboost-python=1.84.0
  - libboost-python-devel=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libhwloc=2.10.0
  - libhwy=1.1.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libopencv=4.9.0
  - libopenvino=2024.1.0
  - libopenvino-arm-cpu-plugin=2024.1.0
  - libopenvino-auto-batch-plugin=2024.1.0
  - libopenvino-auto-plugin=2024.1.0
  - libopenvino-hetero-plugin=2024.1.0
  - libopenvino-ir-frontend=2024.1.0
  - libopenvino-onnx-frontend=2024.1.0
  - libopenvino-paddle-frontend=2024.1.0
  - libopenvino-pytorch-frontend=2024.1.0
  - libopenvino-tensorflow-frontend=2024.1.0
  - libopenvino-tensorflow-lite-frontend=2024.1.0
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvpx=1.14.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=18.1.5
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mpfr=4.2.1
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nd2reader=3.3.0
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.3
  - notebook-shim=0.2.4
  - opencv=4.9.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.0
  - orc=2.0.1
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=24.0
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pims=0.6.1
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.2
  - py-opencv=4.9.0
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pygments=2.18.0
  - pyobjc-core=10.2
  - pyobjc-framework-cocoa=10.2
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qudida=0.0.4
  - rav1e=0.6.6
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.1
  - scikit-image=0.22.0
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - send2trash=1.8.3
  - setuptools=70.0.0
  - six=1.16.0
  - slicerator=1.1.0
  - snappy=1.2.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - svt-av1=2.1.0
  - tbb=2021.12.0
  - tblib=3.0.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tifffile=2024.5.22
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4
  - tqdm=4.66.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing_utils=0.1.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xmltodict=0.13.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - flatbuffers==24.3.25
      - gast==0.4.0
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - h5py==3.11.0
      - keras==2.13.1
      - keras-tuner==1.4.7
      - kt-legacy==1.0.5
      - libclang==18.1.1
      - markdown==3.6
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-macos==2.13.0
      - termcolor==2.4.0
      - typing-extensions==4.5.0
      - werkzeug==3.0.3
      - wrapt==1.16.0
