name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - albumentations
  - boost
  - dask
  - gudhi
  - jupyterlab
  - matplotlib
  - networkx
  - opencv
  - python>=3.8
  - scikit-learn
  - scipy
  - setuptools
  - tensorflow
  - keras-tuner
  - pillow
  - scikit-image
  - tqdm
  - pip:
    - "fl_tissue_model_tools@git+https://github.com/fogg-lab/tissue-model-analysis-tools.git#subdirectory=src"
